pipeline {
  environment {
    imagename = "kammana/hariapp:${DOCKER_TAG}"
    DOCKER_TAG = getVersion()
    ecrurl = "https://828556645578.dkr.ecr.us-east-2.amazonaws.com"
    ecrcredentials = "ecr:us-east-2:ecr-ismail"
    dockerImage = ''
    }

  stages {
    stage('SCM Checkout'){
        git 'https://github.com/mmadsen340/udemy_jenkins_ansible.git'
    }

    stage('Download Approved war file'){
            withAWS(region:'us-east-1',credentials:'artifact_repository') 
            {
                s3Download(bucket: 'artifact-repository-807271945287', file: 'target/', force: true, path: 'dockeransible/')
            }
        }

    stage('Building image') {
      steps{
        script {
          dockerImage = docker.build imagename
        }
      }
    }
  }

def getVersion(){
    def commitHash = sh label: '', returnStdout: true, script: 'git rev-parse --short HEAD'
    return commitHash
}