def getVersion(){
    def commitHash = sh label: '', returnStdout: true, script: 'git rev-parse --short HEAD'
    return commitHash
}

pipeline {
  environment {
    imagename = "hariapp:${DOCKER_TAG}"
    DOCKER_TAG = getVersion()
    ecrurl = "807271945287.dkr.ecr.us-east-1.amazonaws.com"
    repo_name = "madsen-lab-jenkinslab"
    ecrcredentials = "ecr:us-east-1:madsen-lab-jenkinslab"
    }
  agent any
  stages {
    stage('SCM Checkout'){
      steps{
        git 'https://github.com/mmadsen340/udemy_jenkins_ansible.git'
      }
    }

    stage('Download Approved war file'){
      steps{
            withAWS(region:'us-east-1',credentials:'artifact_repository') 
            {
                s3Download(bucket: 'artifact-repository-807271945287', file: 'dockeransiblejenkins/target', path: 'dockeransible/', force: true)
            }
       }
    }

    stage('Building image') {
      steps{
        sh "docker build dockeransiblejenkins/ -t $ecrurl/$repo_name-$imagename"
      }
    }

    stage('Push Docker Image') {
      steps{
        sh "docker push $ecrurl/$repo_name-$imagename"
      }
    }
  }
}