node{
    stage('SCM Checkout'){
        git 'https://github.com/mmadsen340/udemy_jenkins_ansible'
    }
    stage('Compile-Package'){
        // Get maven home path (this is for mvn command not found)
        def mvnHome = tool name: 'maven-3', type: 'maven'
        sh "${mvnHome}/bin/mvn package"
    }
}