node{
    stage('SCM Checkout'){
        git 'https://github.com/mmadsen340/udemy_jenkins_ansible'
    }
    stage('Download Approved war file'){
       stage('Download-Package'){
            withAWS(region:'us-east-1',credentials:'artifact_repository') 
            {
                s3Download(bucket: 'artifact-repository-807271945287', file: 'jenkins-deploy/target/myweb-0.0.12.war', force: true, path: 'jenkins-deploy/')
            }
        }
    }
    stage('Deploy to Tomcat'){
      sshagent(['jenkins_ssh']) {
         sh 'scp -o StrictHostKeyChecking=no jenkins-deploy/target/*.war jenkins@192.168.86.18:/opt/tomcat/webapps/'
      }
   }
}